"""Unified guidance engine for portrait photography.

This module is the single source of truth for "what should happen next" in a
portrait shoot.  It replaces duplicated if/else chains that were scattered
across suggestion.py and photographer_cues.py.

Design principles:
  - One PRIMARY instruction per frame (最多加一个 SECONDARY).
  - Three result states: ADJUST / HOLD / INSUFFICIENT_EVIDENCE.
  - Priority: visibility > silhouette conflict > balance > body curve > head > composition.
  - Cues must be speakable to a model — no jargon, no abstract concepts.
  - Internal direction uses semantic enum (never bare "left"/"right").
  - Cue text is generated by a render layer, not hardcoded in logic.
"""
from __future__ import annotations

import dataclasses
from enum import Enum
from typing import Optional

from core.action_classifier import ActionCategory, ActionResult
from core.camera_analyzer import CameraResult, ShotType
from core.composition import CompositionResult
from core.orientation import FacingDirection, OrientationResult


# ---------------------------------------------------------------------------
# Direction enum — semantic, unambiguous
# ---------------------------------------------------------------------------

class Direction(Enum):
    """Semantic direction for guidance actions.

    SUBJECT_* = relative to the subject's body (your left, your right).
    IMAGE_*   = relative to the image frame (left side of the photo).
    POSTURAL  = body-mechanics directions (not left/right).
    STATE     = hold / maintain current state.
    CAMERA    = photographer movement.
    """
    # Subject-relative
    SUBJECT_LEFT = "subject_left"
    SUBJECT_RIGHT = "subject_right"
    # Postural / body mechanics
    OUTWARD = "outward"
    BACKWARD = "backward"
    FORWARD = "forward"
    STAGGER = "stagger"
    SHIFT = "shift"
    CURVE = "curve"
    TILT = "tilt"
    TURN_BACK = "turn_back"
    # State
    HOLD = "hold"
    # Camera
    CAMERA_BACK = "camera_back"
    CAMERA_FORWARD = "camera_forward"


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

class GuidanceState(Enum):
    ADJUST = "adjust"
    HOLD = "hold"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class GuidancePriority(Enum):
    VISIBILITY = 1
    SILHOUETTE = 2
    BALANCE = 3
    BODY_CURVE = 4
    HEAD_GAZE = 5
    COMPOSITION = 6


@dataclasses.dataclass(frozen=True)
class GuidanceAction:
    priority: GuidancePriority
    category: str          # "model" | "camera" | "composition"
    target: str            # e.g. "legs", "left_arm", "head", "torso"
    direction: Direction   # semantic direction, never ambiguous
    reason: str            # technical explanation (language-independent concept)
    stop_condition: Optional[str] = None
    cue: str = ""          # populated by render_cue(); empty = needs rendering


@dataclasses.dataclass(frozen=True)
class GuidanceResult:
    state: GuidanceState
    primary: Optional[GuidanceAction]
    secondary: Optional[GuidanceAction]
    all_actions: tuple[GuidanceAction, ...]
    hold_message: str = ""

    def speakable(self, lang: str = "zh") -> str:
        """The instruction to actually say on set."""
        if self.state == GuidanceState.HOLD:
            return self.hold_message
        if self.state == GuidanceState.INSUFFICIENT_EVIDENCE:
            return _HOLD_FALLBACK[lang]
        parts = []
        if self.primary:
            parts.append(self.primary.cue or render_cue(self.primary, lang))
        if self.secondary:
            parts.append(self.secondary.cue or render_cue(self.secondary, lang))
        return " ".join(parts) if parts else _DEFAULT_HOLD[lang]


# ---------------------------------------------------------------------------
# Language layer — all speakable text lives here
# ---------------------------------------------------------------------------

_HOLD_FALLBACK = {"zh": "先保持当前动作，我还没看清。", "en": "Hold still, I can't see clearly yet."}
_DEFAULT_HOLD = {"zh": "很好，保持现在的状态。", "en": "Good, hold that."}

# (target, direction) → {lang: template}
# Template variables: {target}
_CUE_TEMPLATES: dict[tuple[str, Direction], dict[str, str]] = {
    # Silhouette: arms
    ("left_arm", Direction.OUTWARD): {
        "zh": "一只手离开身体一点，肘部别夹死。",
        "en": "Move one arm away from your body, don't lock your elbow.",
    },
    # Silhouette: legs
    ("legs", Direction.STAGGER): {
        "zh": "两条腿前后错一点，别让膝盖和脚踝落在同一条线上。",
        "en": "Stagger your legs slightly, keep knees and ankles on different lines.",
    },
    ("feet", Direction.STAGGER): {
        "zh": "两只脚错开半步，脚尖稍微转出去一点。",
        "en": "Offset your feet half a step, turn your toes out slightly.",
    },
    # Balance
    ("weight", Direction.SHIFT): {
        "zh": "重心放到一条腿上，另一条腿放松一点。",
        "en": "Shift your weight to one leg, relax the other.",
    },
    ("weight", Direction.HOLD): {
        "zh": "很好，先别把两条腿收齐，保持这个高低差。",
        "en": "Good, keep that weight difference, don't even out.",
    },
    # Body curve
    ("torso", Direction.CURVE): {
        "zh": "给躯干加一点弧线，一侧肩稍高或身体略向一侧弯。",
        "en": "Add a slight curve to your torso, raise one shoulder or lean slightly.",
    },
    # Head / gaze
    ("head", Direction.TILT): {
        "zh": "身体先不动，下巴往一侧偏一点，看我。",
        "en": "Keep your body still, tilt your chin slightly to one side, look at me.",
    },
    ("head", Direction.TURN_BACK): {
        "zh": "身体保持背面，只回一点头，别整个人转回来。",
        "en": "Keep your back to me, just turn your head slightly, don't turn around.",
    },
    # Composition: subject-relative directions
    ("body", Direction.SUBJECT_RIGHT): {
        "zh": "动作往你的右边打开一点。",
        "en": "Open your movement toward your right.",
    },
    ("body", Direction.SUBJECT_LEFT): {
        "zh": "动作往你的左边打开一点。",
        "en": "Open your movement toward your left.",
    },
    ("body_position", Direction.SUBJECT_RIGHT): {
        "zh": "主体严重偏画面左侧，需要整体向你的右边移动。",
        "en": "You're far to the left of frame, move toward your right.",
    },
    ("body_position", Direction.SUBJECT_LEFT): {
        "zh": "主体严重偏画面右侧，需要整体向你的左边移动。",
        "en": "You're far to the right of frame, move toward your left.",
    },
    # Camera
    ("framing", Direction.CAMERA_BACK): {
        "zh": "动作幅度小一点，先把手和脸留在画面里。",
        "en": "Keep movements small, keep your hands and face in frame.",
    },
    ("distance", Direction.CAMERA_FORWARD): {
        "zh": "先把人物放大到可读范围。",
        "en": "Move closer to fill the frame with the subject.",
    },
}

_FALLBACK_CUE = {
    "zh": "保持自然，我会根据画面继续调整。",
    "en": "Stay natural, I'll adjust based on the shot.",
}


def render_cue(action: GuidanceAction, lang: str = "zh") -> str:
    """Generate a speakable cue from the action's semantic fields."""
    key = (action.target, action.direction)
    template = _CUE_TEMPLATES.get(key)
    if template:
        return template.get(lang, template.get("zh", _FALLBACK_CUE["zh"]))
    return _FALLBACK_CUE.get(lang, _FALLBACK_CUE["zh"])


def _make_action(
    priority: GuidancePriority,
    category: str,
    target: str,
    direction: Direction,
    reason: str,
    stop_condition: str | None = None,
    lang: str = "zh",
) -> GuidanceAction:
    """Create a GuidanceAction with cue rendered from the language layer."""
    action = GuidanceAction(priority, category, target, direction, reason, stop_condition)
    # Frozen dataclass, so we need to set cue via object.__setattr__
    object.__setattr__(action, "cue", render_cue(action, lang))
    return action


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _f(action: ActionResult, key: str, default: float = 0.0) -> float:
    return float(action.features.get(key, default))


# ---------------------------------------------------------------------------
# Guidance generators (ordered by priority)
# ---------------------------------------------------------------------------

def _check_visibility(action: ActionResult, pose) -> list[GuidanceAction]:
    """Priority 1: Check if key body parts are visible/occluded."""
    return []


def _check_silhouette(action: ActionResult, lang: str = "zh") -> list[GuidanceAction]:
    """Priority 2: Resolve silhouette conflicts (limbs merging with torso)."""
    actions = []
    elbow_l = action.joint_angles.get("left_elbow", 180.0)
    elbow_r = action.joint_angles.get("right_elbow", 180.0)
    hands_up = bool(_f(action, "hands_above_shoulders", 0.0))

    if not hands_up and elbow_l >= 165 and elbow_r >= 165:
        actions.append(_make_action(
            GuidancePriority.SILHOUETTE, "model", "left_arm", Direction.OUTWARD,
            "双臂贴近躯干会让轮廓粘在一起。",
            "手臂和躯干之间能看到空隙就停。",
            lang=lang,
        ))

    knee_avg = _f(action, "knee_angle_avg", 150.0)
    knee_diff = _f(action, "knee_angle_diff", 0.0)
    stance = _f(action, "stance_width", 0.1)
    # Don't suggest staggering legs that are already asymmetric
    # Sitting/squatting naturally has bent knees — not a silhouette problem
    if knee_avg < 125 and knee_diff < 15 and action.category not in {ActionCategory.SITTING, ActionCategory.SQUATTING}:
        actions.append(_make_action(
            GuidancePriority.SILHOUETTE, "model", "legs", Direction.STAGGER,
            "弯曲腿部已经形成动作，可通过前后层次让轮廓更清楚。",
            "两条腿的轮廓能分清就停。",
            lang=lang,
        ))
    elif stance < 0.04 and knee_avg > 155:
        actions.append(_make_action(
            GuidancePriority.SILHOUETTE, "model", "feet", Direction.STAGGER,
            "当前站姿较窄且对齐，可以用很小的脚位变化增加层次。",
            lang=lang,
        ))

    return actions


def _check_balance(action: ActionResult, lang: str = "zh") -> list[GuidanceAction]:
    """Priority 3: Balance and symmetry — weight distribution."""
    actions = []
    knee_diff = _f(action, "knee_angle_diff", 0.0)
    ankle_diff = _f(action, "ankle_y_diff", 0.0)
    stance = _f(action, "stance_width", 0.1)

    if knee_diff < 10 and ankle_diff < 0.08 and stance < 0.12:
        actions.append(_make_action(
            GuidancePriority.BALANCE, "model", "weight", Direction.SHIFT,
            "当前下肢接近对称，容易形成僵硬的站姿。",
            "两条腿的弯曲程度明显不一样就停。",
            lang=lang,
        ))
    elif knee_diff > 20 or ankle_diff > 0.10:
        actions.append(_make_action(
            GuidancePriority.BALANCE, "model", "weight", Direction.HOLD,
            "当前已经有明显重心差，继续校正反而可能损失自然感。",
            lang=lang,
        ))

    return actions


def _check_body_curve(action: ActionResult, lang: str = "zh") -> list[GuidanceAction]:
    """Priority 4: Add body curves (shoulder-hip offset, torso axis)."""
    actions = []
    shoulder_y = _f(action, "shoulder_y", 0.5)
    hip_y = _f(action, "hip_y", 0.5)

    if abs(shoulder_y - hip_y) < 0.08:
        actions.append(_make_action(
            GuidancePriority.BODY_CURVE, "model", "torso", Direction.CURVE,
            "肩和髋现在比较接近同一高度，缺少身体曲线。",
            lang=lang,
        ))

    return actions


def _check_head_gaze(orientation: OrientationResult, lang: str = "zh") -> list[GuidanceAction]:
    """Priority 5: Head/gaze direction adjustments."""
    actions = []

    if orientation.facing in (FacingDirection.FRONT, FacingDirection.FRONT_LEFT, FacingDirection.FRONT_RIGHT):
        actions.append(_make_action(
            GuidancePriority.HEAD_GAZE, "model", "head", Direction.TILT,
            "轻微头部偏转通常比整个人转身更适合改善正面平面感。",
            lang=lang,
        ))
    elif orientation.facing in (FacingDirection.BACK, FacingDirection.BACK_LEFT, FacingDirection.BACK_RIGHT):
        actions.append(_make_action(
            GuidancePriority.HEAD_GAZE, "model", "head", Direction.TURN_BACK,
            "可以保留背部轮廓，同时增加面部信息。",
            lang=lang,
        ))

    return actions


def _check_composition(composition: CompositionResult, lang: str = "zh") -> list[GuidanceAction]:
    """Priority 6: Composition-driven adjustments.

    Internal logic uses image-space x coordinate. Direction is expressed
    in SUBJECT space: when the subject is on the image-left (px < 0.38),
    we ask them to move toward their own right (toward image center).
    """
    actions = []
    px, _ = composition.subject_position

    if px < 0.25:
        # Extremely off-center — this is more urgent than body curve
        actions.append(_make_action(
            GuidancePriority.BODY_CURVE, "model", "body_position", Direction.SUBJECT_RIGHT, "主体严重偏画面左侧，需要整体向你的右边移动。",
            lang=lang,
        ))
    elif px < 0.38:
        actions.append(_make_action(
            GuidancePriority.COMPOSITION, "model", "body", Direction.SUBJECT_RIGHT,
            "主体偏画面左侧，把肢体或视线向中央/空白方向展开更容易保持平衡。",
            lang=lang,
        ))
    elif px > 0.75:
        # Extremely off-center
        actions.append(_make_action(
            GuidancePriority.BODY_CURVE, "model", "body_position", Direction.SUBJECT_LEFT, "主体严重偏画面右侧，需要整体向你的左边移动。",
            lang=lang,
        ))
    elif px > 0.62:
        actions.append(_make_action(
            GuidancePriority.COMPOSITION, "model", "body", Direction.SUBJECT_LEFT,
            "主体偏画面右侧，需要把视觉方向留给空白区域。",
            lang=lang,
        ))

    return actions


def _check_camera(camera: CameraResult, lang: str = "zh") -> list[GuidanceAction]:
    """Camera-specific guidance (separate from model instructions)."""
    actions = []

    if camera.subject_ratio > 0.65:
        actions.append(_make_action(
            GuidancePriority.COMPOSITION, "camera", "framing", Direction.CAMERA_BACK,
            "人物已经占据较大画面，复杂动作更容易出框。",
            lang=lang,
        ))

    if camera.shot_type in (ShotType.LONG, ShotType.EXTREME_LONG):
        actions.append(_make_action(
            GuidancePriority.VISIBILITY, "camera", "distance", Direction.CAMERA_FORWARD,
            "人物占画面比例偏小，小人物的复杂姿态很难被读出来。",
            lang=lang,
        ))

    return actions


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_guidance(
    action: ActionResult,
    orientation: OrientationResult,
    camera: CameraResult,
    composition: CompositionResult,
    pose=None,
    lang: str = "zh",
) -> GuidanceResult:
    """Generate prioritized guidance for the current frame.

    Returns at most one PRIMARY and one SECONDARY instruction.
    If the current state is already good, returns HOLD.
    """
    candidates: list[GuidanceAction] = []
    candidates.extend(_check_visibility(action, pose))
    candidates.extend(_check_silhouette(action, lang))
    candidates.extend(_check_balance(action, lang))
    candidates.extend(_check_body_curve(action, lang))
    candidates.extend(_check_head_gaze(orientation, lang))
    candidates.extend(_check_composition(composition, lang))

    camera_actions = _check_camera(camera, lang)

    candidates.sort(key=lambda a: a.priority.value)

    model_actions = [a for a in candidates if a.category == "model"]
    hold_actions = [a for a in model_actions if a.direction == Direction.HOLD]
    adjust_actions = [a for a in model_actions if a.direction != Direction.HOLD]

    # A BALANCE hold at priority 3 means the weight distribution is already good.
    # If the only higher-priority adjusts are SILHOUETTE (priority 2), those are
    # minor refinements — the pose is fundamentally sound, so HOLD.
    balance_holds = [a for a in hold_actions if a.priority == GuidancePriority.BALANCE]
    higher_adjusts = [a for a in adjust_actions if a.priority.value < GuidancePriority.BALANCE.value]

    if balance_holds and not higher_adjusts:
        # Pose is fundamentally good; only minor tweaks remain.
        # Don't nitpick — hold.
        return GuidanceResult(
            state=GuidanceState.HOLD,
            primary=balance_holds[0],
            secondary=None,
            all_actions=tuple(model_actions),
            hold_message=balance_holds[0].cue,
        )

    if hold_actions and not adjust_actions:
        return GuidanceResult(
            state=GuidanceState.HOLD,
            primary=hold_actions[0],
            secondary=None,
            all_actions=tuple(model_actions),
            hold_message=hold_actions[0].cue,
        )

    primary = adjust_actions[0] if adjust_actions else (hold_actions[0] if hold_actions else None)
    secondary = adjust_actions[1] if len(adjust_actions) > 1 else (hold_actions[0] if adjust_actions and hold_actions else None)

    if primary is None and camera_actions:
        primary = camera_actions[0]
        secondary = camera_actions[1] if len(camera_actions) > 1 else None

    all_actions = tuple(model_actions + camera_actions)

    if primary is None:
        return GuidanceResult(
            state=GuidanceState.HOLD,
            primary=None,
            secondary=None,
            all_actions=(),
            hold_message=_DEFAULT_HOLD[lang],
        )

    return GuidanceResult(
        state=GuidanceState.ADJUST,
        primary=primary,
        secondary=secondary,
        all_actions=all_actions,
    )


def guidance_for_reference(
    reference_delta: dict,
    current_action: ActionResult,
    orientation: OrientationResult,
    lang: str = "zh",
) -> GuidanceResult:
    """Generate guidance that accounts for reference photo comparison."""
    return GuidanceResult(
        state=GuidanceState.ADJUST,
        primary=None,
        secondary=None,
        all_actions=(),
    )




